### ISSUE TITLE
ENTREGA HITO EXTRAORDINARIO

### ISSUE THREAD

**Issue by DavidBrando** [villagra-abp/code#61]
**Todos los entregables están incluidos en el juego**

# **[JUEGO](https://github.com/ABPMultimediaUA/code/tree/master/ENTREGA/JUEGO/spaceShip1414/x64/Debug)**

# V1

##### GUIA DE IMPLEMENTACIÓN
- [x] Creación de una maquina de estados finitas.
- [ ] Gestionar los cambios de estados dependiendo de lo que vea el enemigo o su árbol de decisiones.
##### TRABAJO REALIZADO
Se ha creado una maquina de estados finita, alojada en el proyecto en MaquinaEstados -> FSM, donde encontramos dos clases MaquinaEstados y Estados.
- La clase Estados contiene toda la información relativa a los Estados.
- La clase MaquinaEstados gestiona una lista de Estados, donde se alojan los estados activos y los inactivos.
↓

## LÓGICA DIFUSA **COMPLETADO 100%**

Se ha empezado a definir la lógica difusa que usará los enemigos a la hora de tomar decisiones. Se van a usar como parámetros difusos la vida del enemigo y la distancia entre el jugador y el enemigo para la toma de decisiones. En un futuro se añadirán la moral del enemigo que estará ligado a su vida, la munición que tiene disponible, entre otros más parámetros.

Están definidas las relaciones de valores de los parámetros que recibe y su traducción a parámetros difusos, aunque quedan por definir las reglas que tiene que seguir la IA y, por consecuente, cambiar los estados de la IA para que ejecute la parte correspondiente.

Los valores que se han elegido han sido fusificados de maneras distintas. La vida ha sido fusificado con una gráfica de 4 triángulos dónde el primero va del valor, en porcentaje de la vida máxima del enemigo, 10% hasta el 30%, representando el estado de _Huir_; el segundo va desde 25% hasta 50% siendo el estado _Baja_; el tercero corresponde a _Media_ representado desde 45% hasta 85%; y por último el estado _Alta_ que se situa desde 75% hasta 100%.

Al igual que la vida, la distanticia también está representada como la distancia máxima que recibe cuando ve al jugador. Los valores de la gráfica están representados en porcentajes: el estado _Cerca_ corresponde al 0% hasta el 35%; estado _Media_ desde el 15% hasta el 80%; y por último el estado _Lejos_ representado desde el 70% hasta el 100%.

Una vez estos valores han sido fusificados se decide cuál de todos esos estados se tiene que ejeuctar en el enemigo. Siguen está tabla:

![imagen](https://cloud.githubusercontent.com/assets/16962423/24700409/60d8a72a-19f7-11e7-986d-2cc3bbf76587.png)

Los cambios de estado se puede ver como cambia el enemigo de color para su gestión. Son parecidos a los colores de la tabla anterior.

Los varlores de moral y cansancio se pasaran a la lógica difusa para ver si su estado es Alta, Media o Baja.
Dependiendo de estos valores se podrán realizar las distintas acciones del enemigo. Estás acciones están condiccionadas al valor de estos valores.

Moral:

- Cuanta menos moral tiene el enemigo, tienes más posibilidades de entrar en el estado escapar obviando a que distancia y la vida restante que tenga.

- Cuando te quitan vida se reduce la moral un porcentaje equivalente al daño recibido.

Cansancio:

- Cuanto más cansancio tengas, la velocidad se ve reducida hasta que llegas a un punto donde tienes que descansar. El enemigo se para en lugar donde se esté y descansa.

- Cuando te bajan la vida, se te aumenta el cansancio proporcional al daño.

- Cuando el cansancio llega a un punto límite, el enemigo tiene que descansar. Mientras descansas se recupera resistencia y regeneras vida hasta cierto punto. Cuando tu cansancio llega a 0 nunca recuperas el valor máximo de este.

##### Acciones IA a implementar
   -  Lógica Difusa.
      - Moral. 
      - Cansancio.
   - Sentidos.
      - Visión cónica.
      - Oído.
   - Memoria

##### Behavior tree
   - [x] Árbol.
     Se ha creado una clase Behavior Tree, donde a partir del root se recorren todos sus nodos.
   - [ ] Selector.
   - [ ] Secuencia.
   - [ ] Condición.
   - [ ] Acción.

- Actualización:
Por el momento se recorre todo el árbol como traza, para comprobar que todos los nodos se insertan bien y son dependientes de sus padres.
Falta programar las contestaciones para poder programar los distintos tipos de nodos.

- Diseño de arboles:
   - [x] CRIA DE ALIEN.
   - [x] BERSERKER.
   - [ ] SOLDADO.
   - [ ] JEFE.

#### CRIA ALIEN
![BT_Cria](https://raw.githubusercontent.com/ABPMultimediaUA/code/master/DOCUMENTACION/IMAGENES%20ISSUES/CRIA.png?token=ANpXkrJSGHq0YlrwbDX38-OK30wr0SR1ks5Y6pTQwA%3D%3D)
#### ALIEN BERSERKER
![BT_Berserker](https://raw.githubusercontent.com/ABPMultimediaUA/code/master/DOCUMENTACION/IMAGENES%20ISSUES/BERSERKER.png?token=ANpXkg2WkAxa6c7xqTT9HARWo1C3eMYCks5Y6pjuwA%3D%3D)

#### ALIEN JEFE
↓
## SISTEMA DE CONTROL DE MOVIMIENTO CON STEERING BEHAVIOURS **COMPLETADO 100%**

Se ha elaborado un sistema para dar naturalidad al movimiento de los enemigos, con el objetivo de que parezcan más humanos. Además, de evitar obstáculos que hay a su paso.

- [x] Seek.
Se mueve con una velocidad lineal hacia un punto.

- [x] Arrive.
Cuando el enemigo esta llegando al objeto, se produce una deceleración y modifica su trayectoria dando la sensación de comportamiento humano.

- [x] Align
Rota el objeto en función de la parte frontal del enemigo, para mirar en que dirección se esta moviendo.

- [x] Path following.
Busca el punto en el que se tiene que mover. Esta ligado al Seek.

- [x] Face.
Busca el punto al que tiene que rotar. Esta ligado al Align.

- [x] Distance of the wall.
Lanza un rayo con el raycasting para saber si es una pared o no, con el objetivo de no chocar con ella y evitar esa colisión. Ligado al seguimiento del líder en Flocking.

- [x] CollisionAvoidance.
Busca dentro de su "vecindario" de enemigos y si se va a provocar una colisión con otro enemigo los enemigos modifican su trayectoria para no chocar.

### SISTEMA DE CONTROL DE MOVIMIENTO CON STEERING

Se ha elaborado un sistema para dar naturalidad al movimiento de los enemigos, con el objetivo de que parezcan más humanos. Además, de evitar obstáculos que hay a su paso.

- Seek.
Se mueve con una velocidad lineal hacia un punto.

- Arrive.
Cuando el enemigo esta llegando al objeto, se produce una deceleración y modifica su trayectoria dando la sensación de comportamiento humano.

- Align
Rota el objeto en función de la parte frontal del enemigo, para mirar en que dirección se esta moviendo.

- Path following.
Busca el punto en el que se tiene que mover. Esta ligado al Seek.

- Face.
Busca el punto al que tiene que rotar. Esta ligado al Align.

-  Distance of the wall.
Lanza un rayo con el raycasting para saber si es una pared o no, con el objetivo de no chocar con ella y evitar esa colisión. Ligado al seguimiento del líder en Flocking.

- CollisionAvoidance.
Busca dentro de su "vecindario" de enemigos y si se va a provocar una colisión con otro enemigo los enemigos modifican su trayectoria para no chocar.

↓
## SISTEMA DE PERCEPCIÓN SENSORIAL **COMPLETADO 20%**

- [x] Hacer que el enemigo tenga un campo de visión

- [ ] Hacer un rango de escucha

- [ ] Mejorar ese campo para que sea variable si colisiona contra una pared u otro objeto

- [ ] Mejorar el rango de escucha para que varie dependiendo de donde se origine el ruido (si se crea detrás de una pared se oirá menos)

↓

## SISTEMA DE WAYPOINTS PARA PATHFINDING CONTINUO - **COMPLETADO 100%**

Se ha emplementado un sistema de pathfinding para el enemigo que busca el nodo más cercano a su punto de aparición para luego ir buscando el siguiente punto más cercano. Por ahora no tiene una ruta definida y se va moviendo entre los distintos waypoints creados en el mapa. Los nodos que sigue el enemigo están pintados en el mapa.

El sistema de waypoints que sigue el enemigo usando el pathfinding sus posiciones están creadas en Unity para su exportación. Cuando se lee el fichero exportado de Unity se crean esos waypoints y se completa el grafo de pesos que va a seguir el pathfinding.

Los enemigos tienen waypoints distintos porque hay distintas zonas de waypoints creadas en el mapa, así logramos que los enemigos sean más dependientes de su zona asignada y que patrullen esas zonas.

- [x] Hay que hacer el calculo de los waypoints en el escenario para que solo se calcule una vez
- [x] Hacer que el enemigo no se quede dando vueltas entre 2 waypoints durante mucho tiempo y hacer que cambie.
- [x] Reducir el grafo de cada enemigo y que tenga el waypoint mas cercano que encuentre y 3 o 4 mas para formar su grafo.

- [x] Hacer que el enemigo decida a que waypoint tiene que ir y se diriga hacia él. Una vez llegue, que cambie a otro destino distinto.

↓
## SISTEMA DE NAVMESHES PARA PATHFINDING CONTINUO -  **Completado 80%** _Alpha_
El sistema de Navmeshes ha sido creado mediante código, mediante el siguiente procedimiento.
1. Se crea una matriz de enteros donde el tamaño de cada celda será arbitrario, es decir si el tamaño de cada celda es 5, en el mapa del juego correspondrá a 5x5 pixeles. Es decir si nuestro mapa mide 500x500, tendremos una matriz 100x100.
2. Una vez creada la matriz, la rellenamos la matriz con 0, que significará que en ese hueco no existe ninguna pared y por lo tanto es transitable. Para las paredes usaremos el 1, es decir, no transitable. Para crear estas zonas no transitables, buscaremos el centro de las paredes y su tamaño, para así conseguir rellenar las casillas correspondientes a la pared.
3. El siguiente paso nos hemos basado en algoritmo de "Marching Squares"*, para crear el contorno que rodea a las paredes.
*https://en.wikipedia.org/wiki/Marching_squares
4. Ya hallados los contornos, pasamos a expandir las esquinas vertical y horizontalmente, para así crear regiones de cuatro lados.
5. Creadas las regiones, vamos tratar cada esquina como un nodo, donde hallaremos su matriz de adyacencia. Mediante esta matriz, generaremos las diagonales, que nos dividirá el cuadrado en dos, triangulando así el mapa.
6. Por último, hallamos los puntos medios de estas diagonales y creamos los waypoints en esas posiciones.

- FALTA:
- [ ] Creación de Waypoints.
- [ ] Testear navmesh con el nuevo mapa.

↓
##  FLOCKING: COMPORTAMIENTO GRUPAL EMERGENTE. **COMPLETADO 100%**

El comportamiento Flocking ha sido realizado mediante la creación de una clase que implementa este comportamiento. Esta clase consta de un vector donde se almacenan las entities2D que forman el vecindario y un booleano que indica si es, o no, un lider; para que las entidades tengan un punto a donde ir.

El Flocking consta de 3 tipos distintos de streering behaviors para formar este comportamiento:

- ### La cohesión

Este tipo de comportamiento funciona de tal manera de que, busca las entities que forman el vecindario para encontrar su centro de masas y dirigirse hacia él para poder juntarse con ese grupo. Luego retorna el vector unitario correspondiente a ese centro de masas.

- ### Separación

Este comportamiento funciona de tal manera de que, separa a dos entidades aplicando un vector unitario que las aleja en una dirreción proporcional a la que se están moviendo (aporximadamente 180 grados). Este vector se retorna para su posterior aplicación.

- ### Alineación

Con este comportamiento lo que queremos simular es que todas las entidades del vecindario sigan la misma dirección que tiene el lider, para que todas se muevan al unísono y de manera uniforme. El vector calculado es un vector unitario.

↓
## COMUNICACIÓN SIMULADA BÁSICA ENTRE NPCs (BLACKBOARD) **COMPLETADO 0%**
↓
## SISTEMA DE MEMORIA DE ESTADO Y REACCIÓN PARA NPCs **COMPLETADO 0%**

- [ ] Hacer que el enemigo recuerde si las puertas estaban cerradas o abiertas.

- [ ] Hacer que el enemigo recuerde puntos donde el jugador ha sido visto frecuentemente

- [ ] Que el enemigo reaccione al ver al jugador y decida que hacer

↓
## EDITOR IN-GAME DE PARÁMETROS Y COMPORTAMIENTOS DE LA IA **COMPLETADO 0%**

# V2

## DISEÑO Y CREACIÓN DE NIVELES V1.0 -  COMPLETADO 50%

- [x]  NIVEL 1.

↓
## MECÁNICAS BÁSICAS ENTIDADES SIN IA -  COMPLETADO 70%

- [x] Animación de abierto/cerrado.
      -Animación completada a falta de pulir tamaño de apertura.

- [x] Estados de puerta: 
      - Abierta
      - Cerrada
      - Bloqueada (necesita una llave)

- [ ] Ascensor. Cambio de escenario, mediante animación.

     - [x] Tipos de puerta.
            - Ascensor.
            - Puerta rectangular pequeña.
            - Puerta rectangular normal.
            - Puerta rectangular grande.
            - Puerta dividida en dos.
     - [x] Tipos de movimiento.
            - Arriba.
            - Derecha.
            - Ambas direcciones laterales.
            - Ambas direcciones diagonales.
     - [x] Modificar proyecto de Unity para implementar estas puertas.

#### Implementar los distintos objetos consumables.

- [x] Llaves

##### Munición (de distintos tipos)

- [x] Munición de pistola

- [x] Munición de subfusil

- [x] Munición de escopeta

- [x] Munición de lanzagranadas

- [x] Botiquines

- [ ] Barriles explosivos

-  Probar los distintos objetos creados:

- [x] Llaves

- [x] Munición de pistola

- [x] Munición de subfusil

- [x] Munición de escopeta

- [ ] Munición de lanzagranadas

- [x] Botiquines

- [ ] Barriles explosivos

↓
## DISEÑO E IMPLEMENTACIÓN DE LA ARQUITECTURA BASADA EN COMPONENTES.  - COMPLETADO 10%

[COMPONENTES](https://github.com/ABPMultimediaUA/code/tree/master/ENTREGA/HITO%201/Aquitectura%20por%20Componentes)

↓
## SISTEMA DE DEPURACIÓN VISUAL DE LAS FÍSICAS. - COMPLETADO 100%

Se ha creado un sistema de depuración de físicas de Box2D donde nos dibuja en la ventana cuadrados de distintos colores para representar los distintos elementos que corresponden a las físicas. Se dibujan los sensores, las fixtures de colisión, entre otros elementos.
↓
## USO DE TEST DE TRAZADO DE RAYOS Y OTROS TESTS DE FÍSICAS. - COMPLETADO 100%

- [x] Usar el raycasting para saber si un objeto ha colisionado con algun otro

- [x] Usar el raycasting para calcular la distancia entre waypoints del mapa

- [x] Usar el raycasting para saber cuantos objetos hay desde que empieza el rayo hasta que acaba

- [x] Usar el raycasting para ver si un objeto puede reaparecer en ese lugar

↓
## FORMATO PROPIO PARA LA DEFINICIÓN DE LOS NIVELES (DOCUMENTO CON LA ESPECIFICACIÓN DEL FORMATO). COMPLETADO 100%

[DOC](https://github.com/ABPMultimediaUA/code/blob/master/ENTREGA/HITO%201/V2/Documento%20de%20exportacion%20del%20mapa.docx)

↓
## POWERS-UP Y ELEMENTOS ADICIONALES. -  COMPLETADO 100%

Las armas tienen implementado en código la subida de nivel y los aumentos cuando se crean a falta de unir esos aumentos con la tienda de objetos y mejoras.

Falta probar que los aumentos funcionan por falta de la tienda

↓
## IMPLEMENTACIÓN DE CÁMARA INTELIGENTE QUE AJUSTE ÁNGULO Y ZOOM. COMPLETADO 100%

Hay distintas cámaras en el juego. Unas están fijas en una posición y otras rotan conforme el personaje se mueve

↓

### Menú del juego con SFML

El menú del juego se ha hecho usando los elementos que proporcionaba SFML

## OCLUSIONES MEDIANTE PORTALES/PVS COMPLETADO 100%

Los objetos que estan fuera del plano de la cámara no se renderizan

↓
## IMPLEMENTACIÓN DEL HUD. COMPLETADO 100%

Se ha realizado un HUD con SFML para el juego

↓
## IMPLEMANTACIÓN DE CLIPPING @Cucala COMPLETADO 100%

Los modelos no se superponen
↓
## IMPLEMENTACIÓN DE SISTEMAS DE PARTÍCULAS. COMPLETADO 0%

# [TAG](https://github.com/ABPMultimediaUA/code/tree/master/ENTREGA/JUEGO/spaceShip1414/spaceShip1414/graphicEngine)

**TODOS LOS ENTREGABLES SOBRE TAG ESTÁN INCLUIDOS EN EL JUEGO PARA QUE SE VEAN**

## TIPO DE DATOS PARA ENTIDADES TIPO TRANSFORMACIÓN. SALIDA MODO DE TEXTO. _**COMPLETADO: 100%**_
Se ha creado una entidad como de tipo transform la cual tiene diferentes métodos estos utilizan la librería glm para multiplicar matrices, vectores, etc. Estas operaciones sirven para la translación, rotación y escalado.

GLM es una librería matemática que trabaja con matrices y esta destinada al trabajo con gráficos.
↓
## TIPO DE DATOS PARA ENTIDADES TIPO  MALLA. SALIDA MODO DE TEXTO.  **COMPLETADO: 100%**
Se ha creado un estructura de datos tipo malla para guardar las mallas que se cargan de archivos externos. Además hay un recurso de tipo malla donde se gestiona esta estructura.
↓
## TIPO DE DATOS PARA ENTIDADES TIPO CÁMARA Y LUZ. SALIDA MODO DE TEXTO. 7 _**COMPLETADO: 100%**_  
↓
## TIPO DE DATOS PARA ENTIDADES TIPO ANIMACIÓN. SALIDA MODO DE TEXTO. 
↓
## GESTOR DE RECURSOS: PARSER DE OBJETOS EN MÚLTIPLES FORMATOS. SALIDA EN MODO TEXTO. @Cucala _**COMPLETADO: 100%**
El gestor de momento lee diferentes objetos de tipo malla y los guarda en su estructura correcta.
Para esto utilizamos ASSIMP como librería de de tipo parser. Con ASSIMP podemos leer los diferentes objetos y después guardarlos con las estructuras correctas proporcionadas por la librería. 
↓
## VISUALIZACIÓN: VISUALIZADOR OPENGL 4.X SIMPLE CON DATOS POR FICHEROS. SHADER BASICO. @Cucala _**COMPLETADO: 100%**
↓
Que cargan las malas y texturas desde ficheros externos.
## VISUALIZADOR OPENGL 4.X DE LAS ENTIDADES TIPO MALLA. SHADER BÁSICO, INTEGRACIÓN CON EL MOTOR SIN MATERIALES, TEXTURAS, CÁMARA Y LUCES. @Cucala _**COMPLETADO: 100%**
↓
Hay un Shader básico que carga las diferentes mallas con las características básicas de sus materiales.
## VISUALIZADOR OPENGL 4.X DE LAS ENTIDADES TIPO MALLA. SHADER BÁSICO, INTEGRACIÓN CON EL MOTOR CON CÁMARA Y LUCES DE VARIOS TIPOS, VISUALIZACIÓN CON REGISTRO DE CÁMARA Y LUCES. @Cucala _**COMPLETADO: 100%**
↓
## CREACIÓN DE UNA FACHADA ENTRE EL MOTOR Y LA APLICACIÓN. **COMPLETADO 100%**

Tenemos una fachada con el motor gráfico que nos permite crear los elementos necesarios para gestionar el árbol. También tenemos una fachada con nuestro juego y una máquina de estados que gestiona el flujo del juego

↓
## CARGA DE MODELOS EN FORMATO MULTIPLE EN LAS ENTIDADES DE TIPO MALLA. CARGA DE VARIOS FICHEROS PARA ANIMACIÓN. SALIDA MODO TEXTO. 
↓
Se ha creado una entidad tipo TAnimacion que carga una serie de mallas y después gestiona el renderizado de la malla correspondiente mediante un deltaTime.
## INTEGRACIÓN CON EL VIDEOJUEGO. SUSTITUCIÓN MOTOR.  **COMPLETADO 100%*
↓
El juego funciona completamente con el motor gráfico. Esta todo el juego integrado en el motor grafico.
## VISUALIZADOR OPENGL 4.X CON CUATRO SHADERS AVANZADOS. 
↓
## OPTIMIZACIÓN DEL MOTOR. **COMPLETADO 65%**
↓
Se han ido mejorando diferentes factores del motor para que este fusione lo mas fluido posible.
## EFECTOS VISUALES. 
↓
## EXTRAS. 
↓

# RV

## MODELADO Y TEXTURIZADO DE PERSONAJES.
[PERSONAJES](https://github.com/ABPMultimediaUA/code/tree/master/ENTREGA/HITO%20EXTRAORDINARIO/RV/MODELADO%20Y%20TEXTURIZADO/PERSONAJES)

### JUGADOR
[JUGADOR](https://github.com/ABPMultimediaUA/code/tree/master/ENTREGA/HITO%20EXTRAORDINARIO/RV/MODELADO%20Y%20TEXTURIZADO/PERSONAJES/JUGADOR)
[imagen](https://github.com/ABPMultimediaUA/code/blob/master/ENTREGA/HITO%20EXTRAORDINARIO/RV/MODELADO%20Y%20TEXTURIZADO/PERSONAJES/JUGADOR/player.jpg)

### ALIEN BERSERKER
[BERSERKER](https://github.com/ABPMultimediaUA/code/tree/master/ENTREGA/HITO%20EXTRAORDINARIO/RV/MODELADO%20Y%20TEXTURIZADO/PERSONAJES/ALIEN%20BERSERKER)
[imagen](https://github.com/ABPMultimediaUA/code/blob/master/ENTREGA/HITO%20EXTRAORDINARIO/RV/MODELADO%20Y%20TEXTURIZADO/PERSONAJES/ALIEN%20BERSERKER/berserker.jpg)

### ALIEN SOLDADO
[SOLDADO](https://github.com/ABPMultimediaUA/code/tree/master/ENTREGA/HITO%20EXTRAORDINARIO/RV/MODELADO%20Y%20TEXTURIZADO/PERSONAJES/ALIEN%20SOLDADO)
[imagen](https://github.com/ABPMultimediaUA/code/blob/master/ENTREGA/HITO%20EXTRAORDINARIO/RV/MODELADO%20Y%20TEXTURIZADO/PERSONAJES/ALIEN%20SOLDADO/soldado.jpg)

### CRIA DE ALIEN
[CRIA](https://github.com/ABPMultimediaUA/code/tree/master/ENTREGA/HITO%20EXTRAORDINARIO/RV/MODELADO%20Y%20TEXTURIZADO/PERSONAJES/CRIA%20ALIEN)
[imagen](https://github.com/ABPMultimediaUA/code/blob/master/ENTREGA/HITO%20EXTRAORDINARIO/RV/MODELADO%20Y%20TEXTURIZADO/PERSONAJES/CRIA%20ALIEN/cria3.jpg)

## MODELADO Y TEXTURIZADO DE HABITACIONES
[ESCENARIO](https://github.com/ABPMultimediaUA/code/tree/master/ENTREGA/HITO%20EXTRAORDINARIO/RV/MODELADO%20Y%20TEXTURIZADO/ESCENARIO)

[CANTINA](https://github.com/ABPMultimediaUA/code/blob/master/ENTREGA/HITO%20EXTRAORDINARIO/RV/MODELADO%20Y%20TEXTURIZADO/ESCENARIO/CANTINA/cantina.jpg)

[ALMACEN](https://github.com/ABPMultimediaUA/code/blob/master/ENTREGA/HITO%20EXTRAORDINARIO/RV/MODELADO%20Y%20TEXTURIZADO/ESCENARIO/ALMACENES/ALMACEN2.jpg)

[ARSENAL](https://github.com/ABPMultimediaUA/code/blob/master/ENTREGA/HITO%20EXTRAORDINARIO/RV/MODELADO%20Y%20TEXTURIZADO/ESCENARIO/ARSENAL/arsenal.jpg)

[COMISARIA](https://github.com/ABPMultimediaUA/code/blob/master/ENTREGA/HITO%20EXTRAORDINARIO/RV/MODELADO%20Y%20TEXTURIZADO/ESCENARIO/COMISARIA%20CELDA/comisaria.jpg)

[PASILLOS](https://github.com/ABPMultimediaUA/code/blob/master/ENTREGA/HITO%20EXTRAORDINARIO/RV/MODELADO%20Y%20TEXTURIZADO/ESCENARIO/PASILLOS/pasillos.jpg)

[SALA DE ESPERA](https://github.com/ABPMultimediaUA/code/blob/master/ENTREGA/HITO%20EXTRAORDINARIO/RV/MODELADO%20Y%20TEXTURIZADO/ESCENARIO/SALA%20ESPERA/sala%20de%20espera.jpg)

[SALA GENERADOR](https://github.com/ABPMultimediaUA/code/blob/master/ENTREGA/HITO%20EXTRAORDINARIO/RV/MODELADO%20Y%20TEXTURIZADO/ESCENARIO/SALA%20GENERADOR/generador.jpg)

[SALA MANTENIMIENTO](https://github.com/ABPMultimediaUA/code/blob/master/ENTREGA/HITO%20EXTRAORDINARIO/RV/MODELADO%20Y%20TEXTURIZADO/ESCENARIO/SALA%20MANTENIMIENTO/mantenimiento.jpg)

[VESTUARIO](https://github.com/ABPMultimediaUA/code/blob/master/ENTREGA/HITO%20EXTRAORDINARIO/RV/MODELADO%20Y%20TEXTURIZADO/ESCENARIO/VESTUARIO/vestuario.jpg)

### ARMAS
[ARMAS](https://github.com/ABPMultimediaUA/code/tree/master/ENTREGA/HITO%20EXTRAORDINARIO/RV/MODELADO%20Y%20TEXTURIZADO/ARMAS)

[PISTOLA](https://raw.githubusercontent.com/ABPMultimediaUA/code/master/ENTREGA/HITO%20EXTRAORDINARIO/RV/MODELADO%20Y%20TEXTURIZADO/ARMAS/pistola.jpg?token=AIjsjFbvV2fXZUOLy_SDl0xSjvM1NZq7ks5Zb6KswA%3D%3D)

[ESCOPETA](https://raw.githubusercontent.com/ABPMultimediaUA/code/master/ENTREGA/HITO%20EXTRAORDINARIO/RV/MODELADO%20Y%20TEXTURIZADO/ARMAS/escopeta.jpg?token=AIjsjO0L7JRIabMvaBJ5gfNbGpp8DBC3ks5Zb6LjwA%3D%3D)

## ANIMACIONES
[ANIMACIONES](https://github.com/ABPMultimediaUA/code/tree/master/ENTREGA/HITO%20EXTRAORDINARIO/RV/ANIMACIONES)

# PM

### Informes Hito Extraordinario
- [Informe Iteración 1](https://github.com/ABPMultimediaUA/code/blob/master/ENTREGA/HITO%20EXTRAORDINARIO/PM/Informe_Seguimiento_Hito5_Iteracion1.docx)
- [Informe iteración 2](https://github.com/ABPMultimediaUA/code/blob/master/ENTREGA/HITO%20EXTRAORDINARIO/PM/Informe_Seguimiento_Hito5_Iteracion2.docx)
- [Informe Iteración 3](https://github.com/ABPMultimediaUA/code/blob/master/ENTREGA/HITO%20EXTRAORDINARIO/PM/Informe_Seguimiento_Hito5_Iteracion3.docx)

# PD

Entregables:
- [TRAILER](https://github.com/ABPMultimediaUA/code/tree/master/ENTREGA/HITO%20EXTRAORDINARIO/PD/trailer)
[video](https://github.com/ABPMultimediaUA/code/blob/master/ENTREGA/HITO%20EXTRAORDINARIO/PD/trailer/trailer.flv)

- [MAKING OF](https://github.com/ABPMultimediaUA/code/tree/master/ENTREGA/HITO%20EXTRAORDINARIO/PD/making%20of)
[video](https://github.com/ABPMultimediaUA/code/blob/master/ENTREGA/HITO%20EXTRAORDINARIO/PD/making%20of/making%20of.flv)

- [CRÉDITOS](https://github.com/ABPMultimediaUA/code/tree/master/ENTREGA/HITO%20EXTRAORDINARIO/PD/creditos)
[video](https://github.com/ABPMultimediaUA/code/blob/master/ENTREGA/HITO%20EXTRAORDINARIO/PD/creditos/creditos.flv)
